# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78de50575efa2ae0612218854140ef2826aca1685ab107e32c4c2796735cac1a1eb91504455d60c78dad5252d41f1bd26608e953c43425e6c98fa0bcb4727187

test:
  secret_key_base: 1b7ab4b8a2a321930ec1fb5021e2f5d82d452ef4fd78b15672e6b1247f8ba8ae5238a96ff6d8d963ef0b5227385e864809557d651345b7018dfd9f4e8760b639

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
